### ISSUE TITLE
How can I install openwrt+shadowsocks+privoxy?

### ISSUE THREAD

**Issue by yangcin** [sowbug/703n#1]
I config my 703n with your files, it work!
But now i want install shadowsocks and privoxy server.
There're many config files. And I never success.
Could you try it? https://github.com/aa65535

**Comment by sowbug** [comment]
Sorry, I publish solutions for my own problems in the hope they'll help others. I haven't needed to use those features/products, so I won't be working on them.

If you come up with a solution, please submit a pull request.
